/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedQuickNotesRouteImport } from './routes/_authenticated/quick-notes'
import { Route as AuthenticatedGraphRouteImport } from './routes/_authenticated/graph'
import { Route as EmbedNoteNoteIdRouteImport } from './routes/embed/note.$noteId'
import { Route as EmbedCanvasCanvasIdRouteImport } from './routes/embed/canvas.$canvasId'
import { Route as AuthenticatedPluginsPluginIdRouteImport } from './routes/_authenticated/plugins/$pluginId'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes/$noteId'
import { Route as AuthenticatedCanvasCanvasIdRouteImport } from './routes/_authenticated/canvas.$canvasId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuickNotesRoute = AuthenticatedQuickNotesRouteImport.update({
  id: '/quick-notes',
  path: '/quick-notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EmbedNoteNoteIdRoute = EmbedNoteNoteIdRouteImport.update({
  id: '/embed/note/$noteId',
  path: '/embed/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCanvasCanvasIdRoute = EmbedCanvasCanvasIdRouteImport.update({
  id: '/embed/canvas/$canvasId',
  path: '/embed/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPluginsPluginIdRoute =
  AuthenticatedPluginsPluginIdRouteImport.update({
    id: '/plugins/$pluginId',
    path: '/plugins/$pluginId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCanvasCanvasIdRoute =
  AuthenticatedCanvasCanvasIdRouteImport.update({
    id: '/canvas/$canvasId',
    path: '/canvas/$canvasId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/quick-notes': typeof AuthenticatedQuickNotesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/plugins/$pluginId': typeof AuthenticatedPluginsPluginIdRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/embed/note/$noteId': typeof EmbedNoteNoteIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/quick-notes': typeof AuthenticatedQuickNotesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/': typeof AuthenticatedIndexRoute
  '/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/plugins/$pluginId': typeof AuthenticatedPluginsPluginIdRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/embed/note/$noteId': typeof EmbedNoteNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/quick-notes': typeof AuthenticatedQuickNotesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/plugins/$pluginId': typeof AuthenticatedPluginsPluginIdRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/embed/note/$noteId': typeof EmbedNoteNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/login'
    | '/setup'
    | '/graph'
    | '/quick-notes'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/trash'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/plugins/$pluginId'
    | '/embed/canvas/$canvasId'
    | '/embed/note/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/login'
    | '/setup'
    | '/graph'
    | '/quick-notes'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/trash'
    | '/'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/plugins/$pluginId'
    | '/embed/canvas/$canvasId'
    | '/embed/note/$noteId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connect'
    | '/login'
    | '/setup'
    | '/_authenticated/graph'
    | '/_authenticated/quick-notes'
    | '/_authenticated/reminders'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
    | '/_authenticated/trash'
    | '/_authenticated/'
    | '/_authenticated/canvas/$canvasId'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/plugins/$pluginId'
    | '/embed/canvas/$canvasId'
    | '/embed/note/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  EmbedCanvasCanvasIdRoute: typeof EmbedCanvasCanvasIdRoute
  EmbedNoteNoteIdRoute: typeof EmbedNoteNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quick-notes': {
      id: '/_authenticated/quick-notes'
      path: '/quick-notes'
      fullPath: '/quick-notes'
      preLoaderRoute: typeof AuthenticatedQuickNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/embed/note/$noteId': {
      id: '/embed/note/$noteId'
      path: '/embed/note/$noteId'
      fullPath: '/embed/note/$noteId'
      preLoaderRoute: typeof EmbedNoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/canvas/$canvasId': {
      id: '/embed/canvas/$canvasId'
      path: '/embed/canvas/$canvasId'
      fullPath: '/embed/canvas/$canvasId'
      preLoaderRoute: typeof EmbedCanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plugins/$pluginId': {
      id: '/_authenticated/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof AuthenticatedPluginsPluginIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canvas/$canvasId': {
      id: '/_authenticated/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof AuthenticatedCanvasCanvasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedQuickNotesRoute: typeof AuthenticatedQuickNotesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCanvasCanvasIdRoute: typeof AuthenticatedCanvasCanvasIdRoute
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
  AuthenticatedPluginsPluginIdRoute: typeof AuthenticatedPluginsPluginIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedQuickNotesRoute: AuthenticatedQuickNotesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCanvasCanvasIdRoute: AuthenticatedCanvasCanvasIdRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
  AuthenticatedPluginsPluginIdRoute: AuthenticatedPluginsPluginIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  EmbedCanvasCanvasIdRoute: EmbedCanvasCanvasIdRoute,
  EmbedNoteNoteIdRoute: EmbedNoteNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
